FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /backend

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


FROM tomcat:9-jdk17

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /backend/target/*.war /usr/local/tomcat/webapps/ROOT.war

