version: '3'
networks:
  prod:
    driver: bridge

volumes:
  data:
    driver: local

services:
  frontend:
    container_name: frontend
    build:
      context: ./DataStoreFront/
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    networks:
      - prod
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./studentstore/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: database
      MONGODB_PORT: 27017
      MONGODB_DBNAME: test
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
    networks:
      - prod
    depends_on:
      - database

  database:
    container_name: database
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
        - prod
    volumes:
      - data:/data/db
